Style/RegexpLiteral:
  Exclude:
    - Guardfile

require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  Include:
    - Gemfile
    - Guardfile
    - Rakefile
    - bin/planter
    - lib/**/*.rb
  Exclude:
    - pkg/**/*.rb
    - test/*

Style/MutableConstant:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Security/YAMLLoad:
  Exclude:
    - 'lib/**/*.rb'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 45

Metrics/BlockLength:
  Max: 45
  Exclude:
    - Rakefile
    - bin/howzit
    - lib/*.rb

Metrics/ClassLength:
  Max: 300

Metrics/PerceivedComplexity:
  Max: 30

# Metrics/AbcSize:
#   Max: 45

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/AbcSize:
  Enabled: false

Metrics/ModuleLength:
  Max: 174

Security/YAMLLoad:
  Exclude:
    - '**/*.rb'

Style/ModuleFunction:
  Exclude:
    - 'lib/planter/color.rb'

Style/RaiseArgs:
  EnforcedStyle: compact

Style/SlicingWithRange:
  Enabled: false
