#!/bin/bash
export GLI_DEBUG=true
export EDITOR="/usr/bin/vim"
alias b="bundle exec bin/plant"
alias be="bundle exec"
alias quit="exit"

shopt -s nocaseglob
shopt -s histappend
shopt -s histreedit
shopt -s histverify
shopt -s cmdhist

cd /planter
bundle update
gem install pkg/*.gem
