FROM ruby:2.7
RUN mkdir /planter
WORKDIR /planter
RUN gem install bundler:2.2.29
COPY ./docker/sources.list /etc/apt/sources.list
RUN apt-get update -y --allow-insecure-repositories || true
RUN apt-get install -y sudo || true
RUN sudo apt-get install -y less vim || true
COPY ./docker/inputrc /root/.inputrc
COPY ./docker/bash_profile /root/.bash_profile
CMD ["/planter/scripts/runtests.sh"]
