FROM ruby:3.3.0
# RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN mkdir /planter
WORKDIR /planter
RUN gem install bundler:2.2.29
COPY ./docker/sources.list /etc/apt/sources.list
RUN apt-get update -y --allow-insecure-repositories || true
RUN apt-get install -y less vim
COPY ./docker/inputrc /root/.inputrc
COPY ./docker/bash_profile /root/.bash_profile
CMD ["/planter/scripts/runtests.sh"]
